#!/usr/bin/python3

from PIL import Image

def main(imageName):

    im = Image.open(imageName)
    pixel = im.load()
    print (im.size)
    x = im.size [0]
    y = im.size [1]


    for a in range(0,x):     
        for b in range(0,y):
            print(pixel[a,b])
    
main(input("Enter image name. (eg. hello.png) "))

