#!/usr/bin/python3

from PIL import Image

def main(imageName):

    im = Image.open(imageName)
    pixel = im.load()
    array = []
    x = im.size [0]
    y = im.size [1]


    for a in range(0,x):
        for b in range(0,y):
            a1 = bin(pixel[a,b] [0])
            b1 = bin(pixel[a,b] [1])
            c1 = bin(pixel[a,b] [2])
            #tup = (a1, b1, c1)
            array.append(lsb(a1, b1, c1))
    print(array)

    #I don't know what I am doing
    #
    #
    #list_of_pixels = list(array)
    # Do something to the pixels...
    #im2 = Image.new(im.mode, im.size)
    #im2.putdata(list_of_pixels)



def lsb(a1,b1,c1):
    a1 = str(a1)[-2:]
    b1 = str(b1)[-2:]
    c1 = str(c1)[-2:]
    #adding '0'
    if len(a1) == 1:
        a1 = ("0000000"+ a1)
    else:
        a1 = ("000000"+ a1)
    if len(b1) == 1:
        b1 = ("0000000"+ b1)
    else:
        b1 = ("000000"+ b1)
    if len(c1) == 1:
        c1 = ("0000000"+ c1)
    else:
        c1 =  ("000000"+c1)

    return (a1,b1,c1)

main(input("Enter image name. (eg. hello.png) "))

